version: '3.7'

services:
  mysql:
    container_name: mysql
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: way
      MYSQL_ROOT_PASSWORD: 1234
      TZ: Asia/Seoul
    volumes:
      - ./db/mysql/data:/var/lib/mysql
      - ./db/mysql/init:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306
    networks:
      - docker-bridge

  redis:
    container_name: redis
    image: redis
    restart: always
    environment:
      TZ: Asia/Seoul
    volumes:
      - ./redis/data:/data
      - ./redis/conf/redis.conf:/usr/local/conf/redis.conf
    ports:
      - "6379:6379"
    networks:
      - docker-bridge

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
      RABBITMQ_DEFAULT_VHOST: /
      TZ: Asia/Seoul
    ports:
      - 5672:5672   # AMQP default port
      - 15672:15672 # Management UI port
      - 61613:61613 # STOMP protocol port
    networks:
      - docker-bridge

networks:
  docker-bridge:
    driver: bridge
