package way.application.utils.exception;

import org.springframework.http.HttpStatus;

import lombok.Getter;
import lombok.RequiredArgsConstructor;

@Getter
@RequiredArgsConstructor
public enum ErrorResult {

	// BAD_REQUEST
	DTO_BAD_REQUEST_EXCEPTION(
		HttpStatus.BAD_REQUEST.value(),
		"BTO Bad Request Exception",
		"B001"
	),

	MEMBER_SEQ_BAD_REQUEST_EXCEPTION(
		HttpStatus.BAD_REQUEST.value(),
		"MEMBER_SEQ_BAD_REQUEST_EXCEPTION",
		"MSB002"
	),

	SCHEDULE_SEQ_BAD_REQUEST_EXCEPTION(
		HttpStatus.BAD_REQUEST.value(),
		"SCHEDULE_SEQ_BAD_REQUEST_EXCEPTION",
		"SSB003"
	),

	MEMBER_SEQ_NOT_IN_SCHEDULE_BAD_REQUEST_EXCEPTION(
		HttpStatus.BAD_REQUEST.value(),
		"MEMBER_SEQ_NOT_IN_SCHEDULE_BAD_REQUEST_EXCEPTION",
		"MSNISB004"
	),

	PASSWORD_BAD_REQUEST_EXCEPTION(
		HttpStatus.BAD_REQUEST.value(),
		"PASSWORD_BAD_REQUEST_EXCEPTION",
		"PB005"
	),

	SCHEDULE_DIDNT_CREATED_BY_MEMBER_BAD_REQUEST_EXCEPTION(
		HttpStatus.BAD_REQUEST.value(),
		"SCHEDULE_DIDNT_CREATED_BY_MEMBER_BAD_REQUEST_EXCEPTION",
		"SDCBMB008"
	),

	EMAIL_BAD_REQUEST_EXCEPTION(
		HttpStatus.BAD_REQUEST.value(),
		"EMAIL_BAD_REQUEST_EXCEPTION",
		"EB009"
	),

	CODE_BAD_REQUEST_EXCEPTION(
		HttpStatus.BAD_REQUEST.value(),
		"CODE_BAD_REQUEST_EXCEPTION",
		"CB011"
	),

	PASSWORD_MISMATCH_BAD_REQUEST_EXCEPTION(
		HttpStatus.BAD_REQUEST.value(),
		"PASSWORD_MISMATCH_BAD_REQUEST_EXCEPTION",
		"PMB013"
	),

	SELF_FRIEND_REQUEST_BAD_REQUEST_EXCEPTION(
		HttpStatus.BAD_REQUEST.value(),
		"SELF_FRIEND_REQUEST_BAD_REQUEST_EXCEPTION",
		"SFRB015"
	),

	ALREADY_SENT_BAD_REQUEST_EXCEPTION(
		HttpStatus.BAD_REQUEST.value(),
		"ALREADY_SENT_BAD_REQUEST_EXCEPTION",
		"ASB017"
	),

	ALREADY_SENT_BY_FRIEND_BAD_REQUEST_EXCEPTION(
		HttpStatus.BAD_REQUEST.value(),
		"ALREADY_SENT_BY_FRIEND_BAD_REQUEST_EXCEPTION",
		"ASBFB018"
	),

	FEED_SEQ_BAD_REQUEST_EXCEPTION(
		HttpStatus.BAD_REQUEST.value(),
		"FEED_SEQ_BAD_REQUEST_EXCEPTION",
		"FSB019"
	),

	FEED_DIDNT_CREATED_BY_MEMBER_BAD_REQUEST_EXCEPTION(
		HttpStatus.BAD_REQUEST.value(),
		"FEED_DIDNT_CREATED_BY_MEMBER_BAD_REQUEST_EXCEPTION",
		"FDCBMB020"
	),

	MEMBER_CODE_BAD_REQUEST_EXCEPTION(
		HttpStatus.BAD_REQUEST.value(),
		"MEMBER_CODE_BAD_REQUEST_EXCEPTION",
		"MCB021"
	),

	SENDER_SEQ_BAD_REQUEST_EXCEPTION(
		HttpStatus.BAD_REQUEST.value(),
		"SENDER_SEQ_BAD_REQUEST_EXCEPTION",
		"SEB022"
	),

	RECEIVER_SEQ_BAD_REQUEST_EXCEPTION(
		HttpStatus.BAD_REQUEST.value(),
		"RECEIVER_SEQ_BAD_REQUEST_EXCEPTION",
		"REB023"
	),

	FRIENDREQUEST_SEQ_BAD_REQUEST_EXCEPTION(
		HttpStatus.BAD_REQUEST.value(),
		"FRIENDREQUEST_SEQ_BAD_REQUEST_EXCEPTION",
		"FSB026"
	),

	BOOK_MARK_SEQ_BAD_REQUEST_EXCEPTION(
		HttpStatus.BAD_REQUEST.value(),
		"BOOK_MARK_SEQ_BAD_REQUEST_EXCEPTION",
		"BMSB024"
	),

	LOCATION_SEQ_BAD_REQUEST_EXCEPTION(
		HttpStatus.BAD_REQUEST.value(),
		"LOCATION_SEQ_BAD_REQUEST_EXCEPTION",
		"LSB025"
	),

	SENDER_SEQ_MISMATCH_REQUEST_EXCEPTION(
		HttpStatus.BAD_REQUEST.value(),
		"SENDER_SEQ_MISMATCH_BAD_REQUEST_EXCEPTION",
		"SMB027"
	),

	RECEIVER_SEQ_MISMATCH_REQUEST_EXCEPTION(
		HttpStatus.BAD_REQUEST.value(),
		"RECEIVER_SEQ_MISMATCH_REQUEST_EXCEPTION",
		"RMB028"
	),

	START_TIME_BAD_REQUEST_EXCEPTION(
		HttpStatus.BAD_REQUEST.value(),
		"START_TIME_BAD_REQUEST_EXCEPTION",
		"STB029"
	),

	HIDE_FEED_BAD_REQUEST_EXCEPTION(
		HttpStatus.BAD_REQUEST.value(),
		"HIDE_FEED_BAD_REQUEST_EXCEPTION",
		"HFB030"
	),

	CHAT_ROOM_SEQ_BAD_REQUEST_EXCEPTION(
		HttpStatus.BAD_REQUEST.value(),
		"CHAT_ROOM_SEQ_BAD_REQUEST_EXCEPTION",
		"CRIB031"
	),

	CHAT_ROOM_DONT_HAVE_MEMBER_BAD_REQUEST_EXCEPTION(
		HttpStatus.BAD_REQUEST.value(),
		"CHAT_ROOM_DONT_HAVE_MEMBER_BAD_REQUEST_EXCEPTION",
		"CRDHMB032"
	),

	MEMBER_CREATED_SCHEDULE_BAD_REQUEST_EXCEPTION(
		HttpStatus.BAD_REQUEST.value(),
		"MEMBER_CREATED_SCHEDULE_BAD_REQUEST_EXCEPTION",
		"MCSB033"
	),

	MEMBER_ALREADY_ACCEPT_SCHEDULE_BAD_REQUEST_EXCEPTION(
		HttpStatus.BAD_REQUEST.value(),
		"MEMBER_ALREADY_ACCEPT_SCHEDULE_BAD_REQUEST_EXCEPTION",
		"MAASB034"
	),

	// NOT FOUND
	HIDE_FEED_NOT_FOUND_EXCEPTION(
		HttpStatus.NOT_FOUND.value(),
		"HIDE_FEED_NOT_FOUND_EXCEPTION",
		"HFEN001"
	),

	FRIEND_NOT_FOUND_EXCEPTION(
		HttpStatus.NOT_FOUND.value(),
		"FRIEND_NOT_FOUND_EXCEPTION",
		"FN002"
	),

	CHAT_ROOM_DONT_HAVE_MEMBER_NOT_FOUND_EXCEPTION(
		HttpStatus.BAD_REQUEST.value(),
		"CHAT_ROOM_DONT_HAVE_MEMBER_NOT_FOUND_EXCEPTION",
		"CRDHMN003"
	),

	CHAT_ROOM_NOT_FOUND_EXCEPTION(
		HttpStatus.BAD_REQUEST.value(),
		"CHAT_ROOM_NOT_FOUND_EXCEPTION",
		"CRN004"
	),

	// CONFLICT
	USER_ID_DUPLICATION_CONFLICT_EXCEPTION(
		HttpStatus.CONFLICT.value(),
		"USER_ID_DUPLICATION_CONFLICT_EXCEPTION",
		"UIDC001"
	),

	EMAIL_DUPLICATION_CONFLICT_EXCEPTION(
		HttpStatus.CONFLICT.value(),
		"EMAIL_DUPLICATION_CONFLICT_EXCEPTION",
		"EDC002"
	),

	HIDE_FEED_DUPLICATION_CONFLICT_EXCEPTION(
		HttpStatus.CONFLICT.value(),
		"HIDE_FEED_DUPLICATION_CONFLICT_EXCEPTION",
		"HFEC003"
	),

	FEED_DUPLICATION_CONFLICT_EXCEPTION(
		HttpStatus.CONFLICT.value(),
		"FEED_DUPLICATION_CONFLICT_EXCEPTION",
		"FDC004"
	),

	BOOK_MARK_FEED_DUPLICATION_CONFLICT_EXCEPTION(
		HttpStatus.CONFLICT.value(),
		"BOOK_MARK_FEED_DUPLICATION_CONFLICT_EXCEPTION",
		"BMFDC005"
	),

	CHAT_ROOM_MEMBER_DUPLICATION_CONFLICT_EXCEPTION(
		HttpStatus.CONFLICT.value(),
		"CHAT_ROOM_MEMBER_DUPLICATION_CONFLICT_EXCEPTION",
		"CRMDC006"
	),

	CHAT_ROOM_DUPLICATION_CONFLICT_EXCEPTION(
		HttpStatus.CONFLICT.value(),
		"CHAT_ROOM_DUPLICATION_CONFLICT_EXCEPTION",
		"CRDC007"
	),


	// SERVER
	UNKNOWN_EXCEPTION(
		HttpStatus.INTERNAL_SERVER_ERROR.value(),
		"Unknown Exception",
		"S500"
	),

	FIREBASE_CLOUD_MESSAGING_EXCEPTION(
		HttpStatus.INTERNAL_SERVER_ERROR.value(),
		"FIREBASE_CLOUD_MESSAGING_EXCEPTION",
		"S501"
	),

	;

	private final int httpStatus;
	private final String message;
	private final String code;
}
